version: "3.9"

services:
  wspp:
    container_name: my-wspp
    image: wspp
    pull_policy: never
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
